import { StyleSheet } from 'react-native';
import { Colors } from '@/theme/colors';
import { Fonts } from '@/utils/fonts';

export const styles: any = StyleSheet.create({
  scrollContent: {
    paddingHorizontal: 12,
  },
  scrollBody: {
    paddingBottom: 24,
  },
  sectionLabel: {
    marginTop: 14,
    marginHorizontal: 0,
    fontSize: 14,
    color: Colors.darkBlue,
    fontFamily: Fonts.MontserratSemiBold,
    letterSpacing: 0.6,
  },

  startCard: {
    marginTop: 10,
    marginHorizontal: 0,
    backgroundColor: Colors.gray,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 6,
  },
  startIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  startInfo: { flex: 1 },
  startDate: {
    fontSize: 14,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratMedium,
  },
  startTime: {
    marginTop: 2,
    fontSize: 18,
    color: Colors.darkBlue,
    fontFamily: Fonts.PoppinsSemiBold,
  },
  editBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: Colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },

  card: {
    marginTop: 10,
    marginHorizontal: 0,
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },

  fieldLabel: {
    fontSize: 12,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratMedium,
    letterSpacing: 0.4,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 10,
  },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: 'rgba(19,32,75,0.12)',
  },
  chipActive: {
    backgroundColor: Colors.darkBlue,
    borderColor: Colors.darkBlue,
  },
  chipText: {
    fontSize: 14,
    color: Colors.darkBlue,
    fontFamily: Fonts.PoppinsMedium,
  },
  chipTextActive: { color: Colors.white },
  chipRowContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  chipCheckmark: {
    width: 12,
    height: 12,
    backgroundColor: Colors.white,
    borderRadius: 100,
    justifyContent: 'center',
    alignItems: 'center',
  },
  chipCheckmarkHeight: {
    height: 12,
  },

  captureBox: {
    marginTop: 10,
    marginHorizontal: 0,
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 10 },
    elevation: 5,
  },
  captureInner: {
    width: '100%',
    height: 150,
    borderRadius: 12,
    // borderWidth: 1,
    // borderStyle: 'dashed',
    // borderColor: 'rgba(19,32,75,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  capturedImage: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
  },
  cameraCircle: {
    width: 48,
    height: 48,
    borderRadius: 50,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
    elevation: 8,
  },
  captureText: {
    fontSize: 16,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratMedium,
  },
  insightCard: {
    marginTop: 20,
  },
  footer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 20,
    marginTop: 14,
    marginBottom: 4
  },
  prevBtn: {
    height: 45,
    backgroundColor: Colors.gray,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    width: 'auto',
  },
  prevBtnText: {
    color: Colors.red,
    fontSize: 15,
    fontFamily: Fonts.PoppinsMedium,
    paddingRight: 16,
    lineHeight: 15,
  },
  continueArrowCircleLeft: {
    width: 38,
    height: 38,
    borderRadius: 50,
    backgroundColor: Colors.red,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  continueBtn: {
    width: 'auto',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: Colors.darkBlue,
    height: 45,
  },
  continueArrowCircle: {
    width: 36,
    height: 36,
    borderRadius: 50,
    backgroundColor: Colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  continueText: {
    fontSize: 15,
    color: Colors.white,
    fontFamily: Fonts.PoppinsMedium,
    paddingLeft: 16,
    lineHeight: 15,
  },
  deleteImageIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 50,
    backgroundColor: Colors.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageView: {
    width: '100%',
    height: '100%',
    borderRadius: 22,
    backgroundColor: Colors.gray,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

