import { StyleSheet, Platform } from 'react-native';
import { Colors } from '@/theme/colors';
import { Fonts } from '@/utils/fonts';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  headerRightSlot: {
    justifyContent: 'flex-end',
  },
  keyboardAvoidArea: {
    flex: 1,
  },
  keyboardDismissArea: {
    flex: 1,
  },
  progressSection: {
    marginTop: 20,
    paddingHorizontal: 12,
    paddingBottom: 30,
  },
  vitalsText: {
    fontSize: 14,
    color: Colors.darkBlue,
    marginBottom: 4,
    fontFamily: Fonts.MontserratSemiBold
  },
  stepRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  stepText: {
    fontSize: 24,
    color: Colors.red,
    fontFamily: Fonts.PoppinsSemiBold
  },
  percentPill: {
    backgroundColor: Colors.darkBlue,
    paddingHorizontal: 12,
    paddingVertical: 2,
    borderRadius: 50,
  },
  percentText: {
    color: Colors.white,
    fontSize: 12,
    fontFamily: Fonts.MontserratSemiBold
  },
  progressBarBg: {
    height: 5,
    backgroundColor: 'rgba(255,255,255,0.4)',
    borderRadius: 999,
    width: '100%',
    overflow: 'hidden',
    borderWidth: 0
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: Colors.green,
    borderRadius: 999,
  },
  sheet: {
    flex: 1,
    backgroundColor: Colors.white,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: 'hidden',
  },
  card: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 20,
  },
  cardScrollContent: {
    flexGrow: 1,
    paddingBottom: 24,
  },
  questionBlock: {
    marginTop: 28,
    paddingTop: 4,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  questionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    marginBottom: 10,
  },
  questionHeaderContent: {
    flex: 1,
    minWidth: 0,
  },
  questionIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  questionIconText: {
    fontSize: 18,
  },
  questionTitle: {
    fontSize: 16,
    color: Colors.darkBlue,
    lineHeight: 24,
    fontFamily: Fonts.PoppinsBold,
    textAlign: 'left',
  },
  questionDescription: {
    marginTop: 8,
    fontSize: 15,
    lineHeight: 22,
    color: Colors.titleTextColor,
    fontFamily: Fonts.MontserratRegular,
    opacity: 0.6,
    textAlign: 'center',
    marginBottom: 16,
  },
  questionDescriptionNote: {
    fontSize: 15,
    lineHeight: 20,
    color: Colors.darkBlue,
    fontFamily: Fonts.MontserratSemiBold,
    opacity: 1,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#F7F8FA',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 16,

  },
  optionContent: {
    flex: 1,
  },
  optionRowSelected: {
    // backgroundColor: '#EFFFEC',
    // borderColor: '#D4EBD1',
    backgroundColor: 'rgba(110, 191, 98, 0.1)',
    borderColor: 'rgba(110, 191, 98, 0.16)',
    borderWidth: 1,
  },
  radioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#E2E2E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  radioOuterSelected: {
    backgroundColor: Colors.green,
    borderColor: Colors.green,
  },
  radioInnerSelected: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.white,
  },
  checkboxOuter: {
    width: 22,
    height: 22,
    borderRadius: 6,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: '#E2E2E2',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxOuterSelected: {
    backgroundColor: Colors.green,
    borderColor: Colors.green,
  },
  checkboxInnerSelected: {
    color: Colors.white,
    fontSize: 12,
    fontWeight: 'bold',
  },
  optionText: {
    fontSize: 16,
    color: Colors.darkBlue,
    fontFamily: Fonts.MontserratMedium
  },
  optionTextSelected: {
    color: Colors.green,
  },
  textInput: {
    backgroundColor: 'rgba(243, 245, 249, 1)',
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === 'ios' ? 16 : 12,
    color: Colors.darkBlue,
    fontSize: 16,
    fontFamily: Fonts.MontserratSemiBold,
  },
  textInputPlaceholderFont: {
    fontFamily: Fonts.MontserratRegular,
  },
  textAreaInput: {
    minHeight: 100,
  },
  inputWithSuffixWrap: {
    position: 'relative',
    justifyContent: 'center',
  },
  inputWithSuffixTextInput: {
    paddingRight: 72,
  },
  inputSuffixText: {
    position: 'absolute',
    right: 16,
    color: Colors.titleTextColorGray,
    fontSize: 14,
    fontFamily: Fonts.MontserratRegular,
    fontWeight: '400',
  },
  inputSuffixTextOr: {
    fontFamily: Fonts.MontserratBold,
    fontWeight: '400',
  },
  multiTextInputWrap: {
    marginBottom: 16,
  },
  multiTextInputLabel: {
    color: Colors.titleTextColorGray,
    fontSize: 14,
    marginBottom: 8,
    marginLeft: 4,
    fontFamily: Fonts.MontserratRegular,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 20,
    gap: 20,
    paddingHorizontal: 12,
    borderTopColor: Colors.gray,
    borderTopWidth: 1,
  },
  prevBtn: {
    height: 45,
    backgroundColor: Colors.gray,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    width: 'auto',
  },
  prevBtnText: {
    color: Colors.red,
    fontSize: 15,
    fontFamily: Fonts.PoppinsMedium,
    paddingRight: 16,
    lineHeight: 15,
  },
  continueArrowCircleLeft: {
    width: 38,
    height: 38,
    borderRadius: 50,
    backgroundColor: Colors.red,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  continueBtn: {
    width: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: Colors.darkBlue,
    height: 45,
  },
  continueArrowCircle: {
    width: 36,
    height: 36,
    borderRadius: 50,
    backgroundColor: Colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  continueText: {
    fontSize: 15,
    color: Colors.white,
    fontFamily: Fonts.PoppinsMedium,
    paddingLeft: 16,
    lineHeight: 15,
  },
  noteContainer: {
    marginTop: 2,
    marginBottom: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.gray,
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  noteIcon: {
    color: Colors.green,
    marginRight: 6,
    marginTop: 3,
    fontSize: 13,
    fontWeight: '700',
  },
  noteText: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratRegular,
  },
  tagsWrap: {
    marginTop: 6,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tagPill: {
    backgroundColor: '#E5F5E6',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    marginRight: 6,
    marginTop: 4,
  },
  tagText: {
    fontSize: 10,
    color: '#3B8E42',
    fontFamily: Fonts.MontserratSemiBold,
  },
  alertNoteContainer: {
    marginTop: -4,
    marginBottom: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFD7DB',
    borderLeftColor: '#F0424C',
    borderLeftWidth: 2,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  alertIcon: {
    marginRight: 8,
    marginTop: 2,
    color: '#F0424C',
    fontSize: 10,
  },
  alertContent: {
    flex: 1,
  },
  alertTitle: {
    color: Colors.darkBlue,
    fontSize: 14,
    marginBottom: 4,
    fontFamily: Fonts.PoppinsBold,
  },
  alertText: {
    color: Colors.darkBlue,
    fontSize: 15,
    lineHeight: 20,
    fontFamily: Fonts.MontserratRegular,
    opacity: 0.7
  },
  videoContainer: {
    marginBottom: 14,
  },
  videoPlayer: {
    width: '100%',
    height: 180,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#111827',
  },
  videoLinkText: {
    marginTop: 8,
    color: Colors.primary,
    fontSize: 12,
    fontFamily: Fonts.MontserratSemiBold,
  },
  scaleGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
    marginTop: 4,
  },
  scaleItem: {
    width: '18%',
    minWidth: 48,
    borderWidth: 1,
    borderColor: '#E2E2E2',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    backgroundColor: '#F9FAFC',
  },
  scaleItemSelected: {
    borderColor: Colors.green,
    backgroundColor: '#EFFFEC',
  },
  scaleItemText: {
    color: Colors.darkBlue,
    fontSize: 14,
    fontFamily: Fonts.MontserratSemiBold,
  },
  scaleItemTextSelected: {
    color: Colors.green,
  },
  scaleLabelsRow: {
    marginTop: 10,
    marginBottom: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scaleLabelSide: {
    flexDirection: 'row',
    alignItems: 'center',
    columnGap: 8,
  },
  scaleLabelSideRight: {
    justifyContent: 'flex-end',
  },
  scaleLabelIcon: {
    width: 16,
    height: 16,
  },
  scaleLowLabel: {
    fontSize: 12,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratRegular,
  },
  scaleLowLabelActive: {
    color: Colors.darkBlue,
  },
  scaleHighLabel: {
    fontSize: 12,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratSemiBold,
  },
  scaleHighLabelActive: {
    color: Colors.green,
  },
  safetyModalOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: 'rgba(5, 17, 56, 0.45)',
  },
  safetyModalBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(5, 17, 56, 0.45)',
  },
  safetyModalCard: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '88%',
    backgroundColor: Colors.white,
    borderRadius: 24,
    overflow: 'hidden',
    zIndex: 1,
  },
  safetyModalCardInner: {
    position: 'relative',
    maxHeight: '100%',
  },
  safetyModalWatermark: {
    position: 'absolute',
    right: -10,
    bottom: -10,
    fontSize: 96,
    opacity: 0.05,
    zIndex: 0,
  },
  safetyModalScroll: {
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 28,
    zIndex: 1,
  },
  safetyModalIconOuter: {
    alignSelf: 'center',
    width: 65,
    height: 65,
    borderRadius: 36,
    backgroundColor: '#fdebeb',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  safetyModalIcon: {
    flex: 1,
    bottom: 2,
  },
  safetyModalTitle: {
    alignSelf: 'center',
    fontSize: 16,
    color: Colors.red,
    marginBottom: 12,
    fontFamily: Fonts.PoppinsBold,
    textAlign: 'center',
  },
  safetyModalLead: {
    fontSize: 15,
    lineHeight: 22,
    color: Colors.titleTextColorGray,
    textAlign: 'center',
    marginBottom: 24,
    fontFamily: Fonts.MontserratRegular,
    paddingHorizontal: 4,
  },
  safetyModalSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  safetyModalSectionMarginTop: {
    borderTopColor: Colors.gray,
    borderTopWidth: 1,
    paddingTop: 20
  },
  safetyModalSectionIconBox: {
    width: 36,
    height: 36,
    borderRadius: 9,
    backgroundColor: Colors.gray,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    marginTop: 4,
  },
  safetyModalSectionBody: {
    flex: 1,
    paddingTop: 2,
  },
  safetyModalSectionHeading: {
    fontSize: 16,
    color: Colors.darkBlue,
    marginBottom: 1,
    fontFamily: Fonts.PoppinsSemiBold,
  },
  safetyModalSectionText: {
    fontSize: 14,
    lineHeight: 20,
    color: Colors.darkBlue,
    opacity: 0.7,
    fontFamily: Fonts.MontserratRegular,
  },
  safetyModalEmphasis: {
    color: Colors.darkBlue,
    fontFamily: Fonts.MontserratSemiBold,
  },
  safetyModalCloseBtn: {
    width: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    alignSelf: 'center',
    backgroundColor: Colors.gray
  },
  safetyModalCloseIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.red,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 3,
  },
  safetyModalCloseLabel: {
    fontSize: 16,
    color: Colors.red,
    fontFamily: Fonts.PoppinsMedium,
    paddingRight: 16,
  },

  additionalInfoOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: 'rgba(5, 17, 56, 0.45)',
  },
  additionalInfoBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(5, 17, 56, 0.45)',
  },
  additionalInfoCard: {
    width: '100%',
    maxWidth: 400,
    maxHeight: '88%',
    backgroundColor: Colors.white,
    borderRadius: 24,
    overflow: 'hidden',
    zIndex: 1,
  },
  additionalInfoCardInner: {
    position: 'relative',
    maxHeight: '100%',
  },
  additionalInfoWatermark: {
    position: 'absolute',
    right: -24,
    bottom: -24,
    opacity: 0.07,
  },
  additionalInfoScroll: {
    paddingHorizontal: 24,
    paddingTop: 10,
    paddingBottom: 22,
  },
  additionalInfoTopIconOuter: {
    alignSelf: 'center',
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: Colors.gray,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  additionalInfoTopIconInner: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  additionalInfoTitle: {
    alignSelf: 'center',
    fontSize: 16,
    color: Colors.green,
    marginBottom: 10,
    fontFamily: Fonts.PoppinsBold,
    textAlign: 'center',
  },
  additionalInfoLead: {
    fontSize: 15,
    lineHeight: 20,
    color: Colors.darkBlue,
    textAlign: 'center',
    marginBottom: 18,
    fontFamily: Fonts.MontserratRegular,
    paddingHorizontal: 4,
    opacity: 0.7
  },
  additionalInfoSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  additionalInfoSectionIconBox: {
    width: 36,
    height: 36,
    borderRadius: 9,
    backgroundColor: Colors.gray,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
    marginTop: 4,
  },
  additionalInfoSectionBody: {
    flex: 1,
    paddingTop: 1,
  },
  additionalInfoSectionHeading: {
    fontSize: 16,
    color: Colors.darkBlue,
    fontFamily: Fonts.PoppinsSemiBold,
  },
  additionalInfoSectionText: {
    fontSize: 14,
    lineHeight: 20,
    color: Colors.darkBlue,
    fontFamily: Fonts.MontserratRegular,
    opacity: 0.7
  },
  additionalInfoDocCard: {
    backgroundColor: Colors.gray,
    borderRadius: 18,
    padding: 14,
    marginTop: 6,
    marginBottom: 18,
  },
  additionalInfoDocRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  additionalInfoDocIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  additionalInfoDocBody: {
    flex: 1,
  },
  additionalInfoDocLabel: {
    fontSize: 12,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratSemiBold,
    marginBottom: 2,
  },
  additionalInfoDocName: {
    fontSize: 14,
    color: Colors.darkBlue,
    fontFamily: Fonts.PoppinsSemiBold,
  },
  additionalInfoDownloadBtn: {
    width: '100%',
    height: 45,
    backgroundColor: Colors.green,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  additionalInfoDownloadBtnText: {
    color: Colors.white,
    fontSize: 15,
    fontFamily: Fonts.PoppinsMedium,
    paddingRight: 16,
  },
  additionalInfoDownloadIconCircle: {
    width: 38,
    height: 38,
    borderRadius: 50,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 3,
  },
  modalLine: {
    borderTopColor: Colors.gray,
    borderTopWidth: 1,
  },
  additionalInfoNextTitle: {
    fontSize: 16,
    color: Colors.darkBlue,
    marginBottom: 10,
    fontFamily: Fonts.PoppinsBold,
  },
  additionalInfoNextRow: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 10,
  },
  additionalInfoNextIndex: {
    width: 34,
    fontSize: 13,
    color: Colors.green,
    marginTop: 4,
    fontFamily: Fonts.PoppinsBold,
  },
  additionalInfoNextText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratRegular,
  },
  additionalInfoActions: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 20,
    marginTop: 14,
    marginBottom: 4,
  },
});
