import { StyleSheet } from 'react-native';
import { Colors } from '@/theme/colors';
import { Fonts } from '@/utils/fonts';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.white },
  slide: { flex: 1, backgroundColor: Colors.white },
  hero: { flex: 1 },
  heroImage: { width: '100%', height: '100%' },
  skipWrap: {
    position: 'absolute',
    // top: Platform.OS === 'ios' ? 50 : 30,
    top: 14,
    right: 14,
    zIndex: 5,
  },
  skipPill: {
    backgroundColor: 'rgba(255, 255, 255, 0.26)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    fontFamily: Fonts.PoppinsMedium,
    borderColor: Colors.white,
    borderWidth: StyleSheet.hairlineWidth,
  },
  skipText: { color: Colors.white, fontSize: 14, fontFamily: Fonts.PoppinsMedium },
  bottomCard: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    paddingTop: 14,
    backgroundColor: 'transparent',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.35)',
  },
  bottomCardBackground: {
    ...StyleSheet.absoluteFill,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    overflow: 'hidden',
  },
  bottomCardContent: {
    position: 'relative',
    zIndex: 1,
  },
  bottomCardBlurImage: {
    position: 'absolute',
    left: 0,
    transform: [{ scale: 1.08 }],

  },
  bottomCardOverlay: {
    ...StyleSheet.absoluteFill,
    //  backgroundColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.01)',

  },
  dotsRow: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginBottom: 10,
  },
  dot: {
    height: 6,
    width: 6,
    borderRadius: 3,
    backgroundColor: Colors.white,
  },
  dotActive: {
    width: 20,
    borderRadius: 999,
    backgroundColor: Colors.green,
  },
  title: {
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
    marginTop: 4,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  titleWord: { fontSize: 24, fontFamily: Fonts.PoppinsBold },
  titlePrimary: { color: Colors.green },
  titleDark: { color: Colors.white },
  desc: {
    textAlign: 'center',
    color: Colors.white,
    fontSize: 16,
    fontFamily: Fonts.MontserratMedium,
    marginTop: 8,
    lineHeight: 24,
    paddingHorizontal: 14,
  },
  ctaRow: { marginTop: 14, alignItems: 'center', width: '100%' },
  cta: {
    height: 46,
    width: '92%',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.08)',
    position: 'relative',
    overflow: 'visible',
  },
  ctaText: { color: Colors.titleTextColor, fontSize: 16, fontFamily: Fonts.PoppinsMedium },
  ctaIcon: {
    position: 'absolute',
    right: 5,
    height: 35,
    width: 35,
    borderRadius: 50,
    backgroundColor: Colors.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaIconText: { color: Colors.white, fontWeight: '900', fontSize: 16 },
  safeOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    height: 44,
    backgroundColor: 'rgba(0,0,0,0.00)',
  },
  _unused: { color: Colors.bg },
  safe: {
    flex: 1,
    // backgroundColor: Colors.bg,
  },
});

