import { StyleSheet } from 'react-native';
import { Colors } from '@/theme/colors';
import { Fonts } from '@/utils/fonts';

export const styles = StyleSheet.create({
  headerSideRight: {
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  helpButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSideSpacer: {
    width: 34,
    height: 34,
  },
  scrollContent: {
    paddingBottom: 80,
    paddingTop: 16,
    gap: 16,
    paddingHorizontal: 12,
  },
  scrollContentCentered: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingTop: 0,
  },
  emptyStateContainer: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 15,
  },
  emptyStateImage: {
    maxWidth: 300,
    aspectRatio: 390 / 493,
  },
  funQuizLabel: {
    fontSize: 14,
    color: Colors.darkBlue,
    fontFamily: Fonts.MontserratSemiBold,
  },
  stepRow: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepText: {
    fontSize: 20,
    color: Colors.red,
    fontFamily: Fonts.PoppinsSemiBold,
  },
  percentPill: {
    backgroundColor: Colors.darkBlue,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  percentText: {
    fontSize: 12,
    color: Colors.white,
    fontFamily: Fonts.MontserratSemiBold,
  },
  progressTrack: {
    marginTop: 10,
    height: 5,
    borderRadius: 999,
    backgroundColor: Colors.white,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: Colors.green,
  },
  cardArea: {
    paddingVertical: 18,
  },
  questionCard: {
    borderRadius: 18,
    backgroundColor: Colors.white,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 22,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 8,
  },
  questionIconCircle: {
    width: 65,
    height: 65,
    borderRadius: 999,
    backgroundColor: '#EFF4FF',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  questionTitle: {
    fontSize: 20,
    color: Colors.darkBlue,
    fontFamily: Fonts.PoppinsSemiBold,
    textAlign: 'center'
  },
  questionHint: {
    marginTop: 10,
    fontSize: 13,
    color: Colors.titleTextColorGray,
    fontFamily: Fonts.MontserratRegular,
    textAlign: 'center',
    lineHeight: 22,
  },
  optionsList: {
    gap: 12,
    marginTop: 4,
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.gray,
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  optionRowSelectedCorrect: {
    backgroundColor: Colors.darkBlue,
  },
  optionRowSelectedIncorrect: {
    backgroundColor: Colors.white,
    borderWidth: 1.5,
    borderColor: Colors.red,
  },
  optionRadioOuter: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#D8DCE6',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  optionRadioOuterCorrect: {
    backgroundColor: Colors.green,
    borderColor: Colors.green,
  },
  optionRadioOuterIncorrect: {
    backgroundColor: Colors.red,
    borderColor: Colors.red,
  },
  optionText: {
    flex: 1,
    fontSize: 15,
    color: Colors.darkBlue,
    fontFamily: Fonts.MontserratMedium,
    lineHeight: 20,
  },
  optionTextSelected: {
    color: Colors.white,
    fontFamily: Fonts.MontserratSemiBold,
  },
  optionTextIncorrect: {
    color: Colors.darkBlue,
    fontFamily: Fonts.MontserratSemiBold,
  },
  feedbackCard: {
    borderRadius: 16,
    backgroundColor: Colors.white,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    marginTop: 12
  },
  feedbackHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  feedbackTitleCorrect: {
    fontSize: 16,
    color: Colors.green,
    fontFamily: Fonts.MontserratSemiBold,
    lineHeight: 22,
  },
  feedbackTitleIncorrect: {
    fontSize: 16,
    color: Colors.red,
    fontFamily: Fonts.MontserratSemiBold,
    lineHeight: 22,
  },
  feedbackBody: {
    fontSize: 14,
    color: Colors.titleTextColor,
    fontFamily: Fonts.MontserratRegular,
    lineHeight: 22,
  },
  footer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 20,
    marginTop: 20,
    marginBottom: 4,
    paddingBottom: 24,
  },
  prevBtn: {
    height: 45,
    backgroundColor: Colors.gray,
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'center',
    width: 'auto',
  },
  prevBtnText: {
    color: Colors.red,
    fontSize: 15,
    fontFamily: Fonts.PoppinsMedium,
    paddingRight: 16,
    lineHeight: 15,
  },
  continueArrowCircleLeft: {
    width: 38,
    height: 38,
    borderRadius: 50,
    backgroundColor: Colors.red,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  continueBtn: {
    width: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: Colors.darkBlue,
    height: 45,
  },
  continueArrowCircle: {
    width: 36,
    height: 36,
    borderRadius: 50,
    backgroundColor: Colors.green,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  continueText: {
    fontSize: 15,
    color: Colors.white,
    fontFamily: Fonts.PoppinsMedium,
    paddingLeft: 16,
    lineHeight: 15,
  },
});
